### ISSUE TITLE
Styling glitches when condensing status messages together

### ISSUE THREAD

**Issue by capitaineplanete** [ronilaukkarinen/thelounge-theme-midnight#1]
I turned all status messages off, and it's all fine. I just thought you might like to know :)

**Comment by capitaineplanete** [comment]
![image](https://user-images.githubusercontent.com/29466947/140664755-18818b6a-b654-4ddd-b0cc-fb79851fa1de.jpeg)

**Comment by rollecode** [comment]
Thanks for the report. As I always show everything I didn't realize this. I'm quite busy atm but PRs welcome. Will fix in some point.
