### ISSUE TITLE
MOTD box has white text on white background

### ISSUE THREAD

**Issue by brianwoo** [ronilaukkarinen/thelounge-theme-midnight#2]
Hi there,

MOTD seems to have white text with the white background and it's impossible to see the message:

![image](https://user-images.githubusercontent.com/2199825/159095723-e99fe609-54d4-4cb9-9ec2-4d5c26015c7d.png)

**Comment by rollecode** [comment]
Should be rather easy to fix but I haven't seen motd for a very long time so can't really test it out. Can you select the area in devtools to point it out? PRs always welcome.
